version: '3'
services:
  symfony_project_mysql:
    image: mysql:5.7
    container_name: 'symfony_project_mysql'
    restart: unless-stopped
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysqldata:/var/lib/mysql