hello-world:
    path: /hello-world
    controller: App\Controller\HelloController::helloWorld

show-message:
    path: /show-message
    controller: App\Controller\HelloController:showMessage

cadastrar-produto:
    path: /create-product
    controller: App\Controller\HelloController:createProduct
